### ISSUE TITLE
yaml update impacted test

### ISSUE THREAD

**Issue by mattdowle** [Rdatatable/data.table#5339]
2022-02-17
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_data.table.html>.

Please correct before 2022-03-04 to safely retain your package on CRAN.

The CRAN Team

---

```
Test 2033.01 ran without errors but failed check that x equals y:
> x = as_read[c(1L, 24L)]
First 2 of 2 (type 'character'):
[1] "---" "..."
> y = c("---", "---")
First 2 of 2 (type 'character'):
[1] "---" "---"
1 string mismatch
Test 2033.05 ran without errors but failed check that x equals y:
> x = as_read[25:30]
First 6 of 6 (type 'character'):
[1] "---" "a,b,c" "1,3.14159265358979,a"
[4] "2,1,b" "3,2,c" "4,3,d"
> y = tbl_body
First 6 of 6 (type 'character'):
[1] "a,b,c" "1,3.14159265358979,a" "2,1,b"
[4] "3,2,c" "4,3,d" "5,4,e"
6 string mismatches
Test 2033.11 ran without errors but failed check that x equals y:
> x = length(lines)
First 1 of 1 (type 'integer'):
[1] 49
> y = 48L
First 1 of 1 (type 'integer'):
[1] 48
Mean relative difference: 0.02040816
Test 2033.13 ran without errors but failed check that x equals y:
> x = length(lines)
First 1 of 1 (type 'integer'):
[1] 49
> y = 48L
First 1 of 1 (type 'integer'):
[1] 48
Mean relative difference: 0.02040816

Error in test.data.table() :
4 errors out of 10037. Search tests/tests.Rraw.bz2 for test numbers: 2033.01, 2033.05, 2033.11, 2033.13.
Execution halted
```

**Comment by MichaelChirico** [comment]
Hmm I'm not reproducing.

Just did

```
svn update
make
bin/R CMD INSTALL $DATA_TABLE
bin/Rscript -e "library(data.table); test.data.table()"
```

ditto for CRAN (1.14.2):

```
bin/Rscript -e "install.packages('data.table', repos = 'https://cran.r-project.org')"
bin/Rscript -e "library(data.table); test.data.table()"
```

Both pass for me locally

**Comment by MichaelChirico** [comment]
Looks like maybe because of a change in `yaml`:

https://cran.r-project.org/web/packages/yaml/index.html

Just released yesterday and that test is in the csvy region of code

**Comment by MichaelChirico** [comment]
@viking it looks like you broke us :) any insights? I don't see any NEWS.

```
l <- list(
  source = "R[v4.2.0]::data.table[v1.14.2]::fwrite",
  creation_time_utc = "2022-02-18 22:48:03", 
  schema = list(
    fields = list(
      list(name = "a", type = "integer"), 
      list(name = "b", type = "numeric"),
      list(name = "c", type = "character")
    )
  ),
  header = TRUE,
  sep = ",", 
  sep2 = c("", "|", ""),
  eol = "\n",
  na.strings = "",
  dec = ".", 
  qmethod = "double",
  logical01 = FALSE
)
```

## USING yaml 2.3.4:

Output of `writeLines(yaml::as.yaml(l, line.sep = "\n"))`

```
source: R[v4.2.0]::data.table[v1.14.2]::fwrite
creation_time_utc: 2022-02-18 22:48:03
schema:
  fields:
  - name: a
    type: integer
  - name: b
    type: numeric
  - name: c
    type: character
header: yes
sep: ','
sep2:
- ''
- '|'
- ''
eol: |2+

na.strings: ''
dec: '.'
qmethod: double
logical01: no
...
```

## Using previous release 2.2.2

```
source: R[v4.2.0]::data.table[v1.14.2]::fwrite
creation_time_utc: 2022-02-18 22:48:03
schema:
  fields:
  - name: a
    type: integer
  - name: b
    type: numeric
  - name: c
    type: character
header: yes
sep: ','
sep2:
- ''
- '|'
- ''
eol: |2+

na.strings: ''
dec: '.'
qmethod: double
logical01: no
```

Note the new `...` at the end.
