### ISSUE TITLE
Seal of Approval should also check against devel DT

### ISSUE THREAD

**Issue by jangorecki** [Rdatatable/data.table#6927]
As per our internal discussion, we would like that packages which received "Seal of Approval", to be tested in their own CI against development version of data.table (aside from stable CRAN version).

By _development version of data.table_ I mean not the head of master branch (so do not use `install_github`), but the most recent master branch that passed some/basic/all (to be decided) checks.

That will enable us, developers of data.table, to provide more reliable experience for users of those "approved" packages, as any breaking changes (or incompatibility between devel approved and devel data.table) will be detected as soon as possible.

More about seal of approval in: https://github.com/Rdatatable/data.table/blob/master/Seal_of_Approval.md

We are going to provide a template CI yaml file (github/gitlab), which likely won't need any/much changes. Possibly submitting PRs to approved packages.

@Rdatatable/seal-of-approval are welcome to provide their feedback/comments on this idea.

**Comment by tdhock** [comment]
For info, I have already implemented this for my nc package, https://github.com/tdhock/nc/blob/master/.github/workflows/R-CMD-check.yaml
```yaml
    name: ${{ matrix.config.os }} ${{ matrix.config.r }} dtdev=${{ matrix.config.dt-devel }}
    strategy:
      matrix:
        config:
...
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release', dt-devel: true }
...
      - name: dt-devel
        if: matrix.config.dt-devel
        run: R -e 'data.table::update_dev_pkg()'
```

**Comment by jangorecki** [comment]
@tdhock Could you try adding `"https://Rdatatable.gitlab.io/data.table"` to `repos` option instead of calling `update_dev_pkg()`. Then it should be automatically installed in devel version.

**Comment by tdhock** [comment]
where could repos option be changed in the yaml?
One way would be to use extra-repositories parameter of setup-r action, https://github.com/r-lib/actions/tree/v2/setup-r#inputs
but I would like to do that conditionally (only if dt-devel=true).

Anyway, wouldn't that yield the same result as my current solution, which uses update_dev_pkg?

**Comment by jangorecki** [comment]
It would yield the same results but would waste time unnecessarily installing data.table twice, and considering we would like to use it as a template, then best to have it optimal.

**Comment by hadley** [comment]
Two thoughts:

Does this imply that you're planning on making a bunch of breaking changes to data.table in the near future? That seems surprising to me. (And if you're not, why is this necessary?)

The cadence of checks is going to be wrong — the checks will be run when the package author makes changes. If a check fails, it's going to be hard for the author to know whether it was their code or data.table that was responsible. If you're going to recommend this, it seems like you'd want to put the dev data.table check in a separate script and then have that run on a schedule.

**Comment by tdhock** [comment]
I saw this on a student's backpack at the cafeteria today!

![Image](https://github.com/user-attachments/assets/7e46c840-802b-459c-845d-fdc87b158f19)

**Comment by tdhock** [comment]
Using extra-repositories in a separate yaml file seems to work, and looks like this: https://github.com/tdhock/nc/pull/31/files#diff-f200dfc739c7c5cab3d2545e58c77506d8dc0e6eec418ec483799cc74b3381a0

**Comment by tdhock** [comment]
Here is the log from the check on ubuntu with extra-repositories set. https://github.com/tdhock/nc/actions/runs/14708327052/job/41273973086
I see the following line which seems to indicate that data.table was installed from CRAN.
```
  + data.table     1.17.0   [bld][cmp][dl] (5.83 MB)
```
but I also see the table below which seems to indicate that the data.table gitlab.io repository was found
```
Repo status
             name                                                         url     type bioc_version platform        path r_version   ok     ping error
  1          RSPM https://packagemanager.posit.co/cran/__linux__/noble/latest cranlike         <NA>   source src/contrib       4.6 TRUE 0.182305  NULL
  2          CRAN                                    https://cran.rstudio.com/     cran         <NA>   source src/contrib       4.6 TRUE 0.076552  NULL
  3                                   https://rdatatable.gitlab.io/data.table cranlike         <NA>   source src/contrib       4.6 TRUE 0.273566  NULL
```
My interpretation is that extra-repositories adds the new repository with a lower priority. It is documented as "One or more extra CRAN-like repositories to include in the repos global option" on https://github.com/r-lib/actions/tree/v2/setup-r#inputs which does not specify the priority. This interpretation is consistent with https://github.com/r-lib/actions/issues/727#issuecomment-1546047439 which suggests using upgrade: true, which appears in setup-r-dependencies here https://github.com/RMI-PACTA/actions/blob/f1675fb6306154320285b7b004975e988dd421ff/.github/workflows/R-CMD-check.yml#L98 and is documented here https://github.com/r-lib/actions/tree/v2/setup-r-dependencies#usage

**Comment by hadley** [comment]
@tdhock again, I'd recommend running that job on a schedule since data.table development is not synchronised with the development of the dependency.

**Comment by jangorecki** [comment]
Priority is first defined by version, newer should be picked up. If versions are equal then AFAIK by order of repositories provided.
I suspect the installation routine in CI chooses wrong package.
Could you try simple `print(getOption("repos")); install.packages()` call rather than setup-r-dependencies?

**Comment by tdhock** [comment]
I got it to work with `upgrade: 1` and https://github.com/r-lib/actions/issues/1003 says
```
Install/update packages
  ℹ Installing lockfile '.github/pkg.lock'
   
  → Will install 99 packages.
  → Will download 99 packages with unknown size.
...
  + data.table     1.17.99  👷🏻🔧 ⬇
```

**Comment by jangorecki** [comment]
It looks like we don't have recent devel DT for R 4.6, see https://rdatatable.gitlab.io/data.table/web/packages/data.table/index.html
If you switch to R release then should pick up devel DT

**Comment by tdhock** [comment]
@hadley I'm not sure that I understand what you mean by "run on a schedule" but I understand that you are concerned that the package author (me) will not know the source of a failure (my package or data.table-dev). 

I agree that it is a good idea to run the data.table-dev checks in a separate yaml, alongside checks using regular data.table from CRAN. If there is a failure in data.table-dev but not regular data.table from CRAN, then it would be clear that it is an issue with data.table-dev, and I would report the issue to the data.table/issues tracker.

Here is the yaml for checking data.table-dev that I am using. (@jangorecki please use/adapt for your template)

```yaml
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Check with data.table-dev

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} ${{ matrix.config.r }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'devel'}
          - {os: ubuntu-latest,  r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          extra-repositories: https://Rdatatable.gitlab.io/data.table
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Install R Package Build Dependencies on MacOS, from https://github.com/stan-dev/cmdstanr/pull/1072/files
        if: ${{ runner.os == 'macOS' }}
        uses: r-hub/actions/setup-r-sysreqs@v1
        with:
          type: 'minimal'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          upgrade: 1
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
```

**Comment by hadley** [comment]
@tdhock you really want that yaml to run when data.table changes, not just when your package changes. There's no way to do that with Github actions, so I think the best you can do is put run it on a schedule.

**Comment by tdhock** [comment]
So setup-r-dependencies uses pak for installing packages. 
And I don't know how pak works. It seems like there is some caching of packages that were installed in previous CI runs. 
I imagine a situation where the caching would not work for us.
- pak installs data.table version 1.10.99 then caches it
- a new data.table with the same version 1.10.99 is published in our repo
- then pak looks at its cache, sees the old 1.10.99, does not install the new one from our repo.
Is that how pak / setup-r-dependencies works? @gaborcsardi

in that case, we should just use `data.table::update_dev_pkg()` like I originally suggested.

**Comment by jangorecki** [comment]
I thought that lack of R 4.6 package source was the reason why devel DT was not picked up but rather CRAN version.

After a bit of debugging I found out that GH actions are simply not working as expected
https://github.com/jangorecki/dt.revdep/actions/runs/14725394208
https://github.com/jangorecki/dt.revdep/actions/runs/14725476955

at least considering that in R all works very smoothly.
```
$ Rscript -e 'install.packages("dt.revdep", repos=c("https://cloud.r-project.org","file://home/jan/git","https://rdatatable.gitlab.io/data.table/"))'
Installing package into ‘/home/jan/R/x86_64-redhat-linux-gnu-library/4.5’
(as ‘lib’ is unspecified)
also installing the dependency ‘data.table’

trying URL 'https://rdatatable.gitlab.io/data.table/src/contrib/data.table_1.17.99.tar.gz'
...
* DONE (data.table)
* installing *source* package ‘dt.revdep’ ...
** this is package ‘dt.revdep’ version ‘0.0.1’
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package ‘dt.revdep’
    finding HTML links ... done
    man                                     html  
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (dt.revdep)
...
```
https://github.com/jangorecki/dt.revdep

Not sure if it is a bug or a design decision for those CI helpers, anyway not the first one and not the last one.
Cases like that reassures me to use base R and shell whenever possible and be less dependent on helpers. This time fortunately it didn't took much time to track down the issue.

**Comment by gaborcsardi** [comment]
pak does have a cache, but that of course does not matter at all across GitHub Actions workflow runs.

OTOH `setup-r-dependencies` also has a cache that is meant to work across GHA workflow runs. You can turn it off if you want, see the docs.

**Comment by jangorecki** [comment]
Shouldn't cache be working within same version only?
IMO if there is new version of a package available then cache for that package should expire.

**Comment by jangorecki** [comment]
No, we do not want to run tests when data.table changes. That would be very resources wasteful because those rev deps are likely to have much less frequent commits. We want to run their on each of their commits, but using devel DT.

**Comment by jangorecki** [comment]
Not installing the latest available version of a package available in multiple repositories seems to be design decision of `pak` package. It is therefore inherited in R helpers in GH actions.
To force base R behavior `upgrade: 'TRUE'` needs  be used, as spotted by Toby.
Although it won't guarantee the recent devel because of cache used in GH actions. Disabling cache is likely to add much more overhead than installing data.table twice, therefore `data.table::update_dev_pkg()` seems to be ultimately the optimal way.

The following yaml, based on minimal `check-release.yaml` template.

```yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: data.table-devel

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: upgrade data.table to devel
        run: Rscript -e 'data.table::update_dev_pkg()'

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
```
