### ISSUE TITLE
Poor rendering in pkgdown of ?setorderv

### ISSUE THREAD

**Issue by MichaelChirico** [Rdatatable/data.table#6931]
Seen browsing:

![Image](https://github.com/user-attachments/assets/1b851360-b7e7-44e4-a2b4-12a620c7605a)

Not sure if that's on our end or pkgdown:

https://github.com/Rdatatable/data.table/blob/017fad886848a6a3e460d3f0be9acdfe609a9f0e/man/setorder.Rd#L76

**Comment by m-muecke** [comment]
@MichaelChirico the math rendering default has been changed in recent pkgdown versions. One has to opt-in for better latex support.
I usually go with mathjax, should also be the old default:

```yaml
url: https://rdatatable.gitlab.io/data.table

template:
  bootstrap: 5
  light-switch: true
  math-rendering: mathjax
```
